name: Test Action

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "*.md"
  # A pull request sent from a fork of the upstream repository could be manipulated to do harmful things.
  # The upstream repositoryâ€™s maintainer would have no protection against this attack, as pull requests
  # can be sent by anyone who forks the repository on GitHub.
  # This is why we don't run automated tests on every PR.
  # pull_request:
  #  types:
  #    - opened
  #    - synchronize
  #  paths-ignore:
  #    - '*.md'

jobs:
  skipci:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "[Skip CI] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"

  test:
    runs-on: ${{ matrix.os }}
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    strategy:
      max-parallel: 1
      matrix:
        os:
          - "ubuntu-22.04"
          - "macos-latest"
          - "windows-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - run: npm ci

      - name: Remove lint-staged husky
        run: |
          npm uninstall lint-staged husky
          git checkout package-lock.json package.json

      - run: npm run build

      - name: Install Gotestsum
        uses: ./
        with:
          gotestsum_version: 0.4.1

      - name: Validate
        run: gotestsum --version
